app/models.py
from app import db
from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    email = Column(String(120), index=True, unique=True)
    password_hash = Column(String(128), nullable=False)
    translations = relationship('Translation', backref='user', lazy='dynamic')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_latest_translations(self, num=10):
        return Translation.query.filter_by(user_id=self.id).order_by(Translation.time.desc()).limit(10).all()

    def __repr__(self):
        return f'<User {self.email}>'


class Translation(db.Model):
    __tablename__ = 'translation'

    id = Column(Integer, primary_key=True)
    lang_from = Column(String(16))
    lang_detected = Column(String(16))
    lang_to = Column(String(16))
    text_from = Column(Text)
    text_to = Column(Text)
    time = Column(DateTime(timezone=True), default=datetime.utcnow)
    user_id = Column(Integer, ForeignKey('users.id'))

    def __repr__(self):
        return f'<Translation {self.text_from}>'

app/blueprints/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, SelectField

app/blueprints/home/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SelectField, SubmitField
from wtforms.validators import InputRequired
from ...constants.languages import Languages


class TranslateForm(FlaskForm):
    text = TextAreaField("Text",  validators=[InputRequired(message="Text can't be blank")])
    lang_from = SelectField("From",  choices=Languages)
    lang_to = SelectField("To",  choices=Languages)
    # submit = SubmitField('Submit')

app/__init__.py
from flask import Flask, redirect, url_for, abort
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_login import LoginManager, current_user
from sqlalchemy import inspect

app = Flask(__name__)
app.config.from_object(Config)

### DB configuration ###
db = SQLAlchemy(app)
migrate = Migrate(app, db)
login_manager = LoginManager(app)
login_manager.login_view = 'auth.login'


from app import models


@login_manager.user_loader
def load_user(id):
    return models.User.query.get(int(id))


##################
### Blueprints ###
##################
from app.blueprints.home import bp as home_bp
from app.blueprints.dashboard import bp as dashboard_bp
from app.blueprints.auth import bp as auth_bp

app.register_blueprint(home_bp)
app.register_blueprint(auth_bp)
app.register_blueprint(dashboard_bp, url_prefix='/dashboard')


#############
### Admin ###
#############
class MyModelView(ModelView):
    # can_delete = False

    def is_accessible(self):
        return True

    def inaccessible_callback(self, name, **kwargss):
        return redirect('/')



admin = Admin(app)

admin.add_view(MyModelView(models.User, db.session))
admin.add_view(MyModelView(models.Translation, db.session))

app/blueprints/dashboard/__init__.py
from flask import Blueprint

bp = Blueprint('dashboard', __name__)

from . import routes

app/blueprints/dashboard/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user

from app import db
from . import bp


@bp.route('/')
def dashboard():
    latest_translations = current_user.get_latest_translations(15)
    return render_template('dashboard/dashboard.html', latest_translations=latest_translations, user=current_user)

app/blueprints/home/__init__.py
from flask import Blueprint

bp = Blueprint('home', __name__)

from . import routes

app/blueprints/home/routes.py
from flask import render_template, request, send_file
from flask_login import current_user
from . import bp
from .forms import TranslateForm
from app.helpers.aws import AWS_Translate, AWS_Polly, AWS_Transcribe
from app.constants.languages import Languages
from app.models import User, Translation
from app import db


@bp.route('/', defaults={'translation_id': None}, methods=['GET', 'POST'])
@bp.route('/translations/<translation_id>', methods=['GET', 'POST'])
def index(translation_id):
    from_lang = 'en'
    to_lang = 'fr'

    form = TranslateForm()

    last_translations = current_user.get_latest_translations(10) if not current_user.is_anonymous else []

    # TODO: Error handling for incorrect input
    # Detect language
    if request.method == 'POST':
        text = form.text.data
        from_lang = form.lang_from.data
        to_lang = form.lang_to.data

        response = AWS_Translate.translate_text(
            Text=text,
            SourceLanguageCode=from_lang,
            TargetLanguageCode=to_lang
        )
        translated_text = response.get('TranslatedText')

        # Add translation to DB
        translation = Translation(
            lang_from=from_lang,
            lang_detected=from_lang,
            lang_to=to_lang,
            text_from=text,
            text_to=translated_text,
        )
        if not current_user.is_anonymous:
            translation.user_id = current_user.id
        db.session.add(translation)
        db.session.commit()
        return render_template(
            'home/index.html', title='Home', form=form, languages=Languages, from_lang=from_lang, to_lang=to_lang,
            text=text, translated_text=translated_text, last_translations=last_translations)

    translation = Translation.query.filter_by(id=translation_id).first()

    form.lang_from.data = ((translation and translation.lang_from) or from_lang)
    form.lang_to.data = ((translation and translation.lang_to) or to_lang)

    return render_template(
        'home/index.html', title='Home', languages=Languages, form=form, from_lang=from_lang, to_lang=to_lang,
        last_translations=last_translations, translation=translation)


# @bp.route('/voice', methods=['GET', 'POST'])
# def text_to_speech():
#     response = AWS_Polly.synthesize_speech(VoiceId='Joanna',
#                                            OutputFormat='mp3',
#                                            Text='This is a sample text to be synthesized.')

#     with open('/tmp/speech.mp3', 'wb') as file:
#         file.write(response['AudioStream'].read())

#     job_name = "job name"
#     AWS_Transcribe.start_transcription_job(
#         TranscriptionJobName=job_name,
#         Media={'MediaFileUri': '/tmp/speech.mp3'},
#         MediaFormat='mp3',
#         LanguageCode='en-US'
#     )
#     while True:
#         status = transcribe.get_transcription_job(TranscriptionJobName=job_name)
#         if status['TranscriptionJob']['TranscriptionJobStatus'] in ['COMPLETED', 'FAILED']:
#             break
#         print("Not ready yet...")
#         time.sleep(5)
#     print(status)
#     return send_file("/tmp/speech.mp3", as_attachment=True)

app/templates/_layout/_flash_messages.html
<section id="flash-messages" class="flash-messages">
  {% with messages = get_flashed_messages() %} 
  {% if messages %}
    {% for message in messages %}
    <span class="flash-messages__item">{{message}}</span>
    {% endfor %}
  {% endif %} 
  {% endwith %}
</section>

app/templates/_layout/_footer.html
<footer class="page-footer grey lighten-2">
	<div class="footer-copyright">
		<div class="container black-text">
			Copyright © 2020 Translator Inc. All rights reserved.
			<div class="right">
				<a class="black-text" href="#!"><u>Terms of Use</u></a>
				<span>|</span>
				<a class="black-text" href="#!"><u>Privacy Policy</u></a>
			</div>
		</div>
	</div>
</footer>

app/templates/_layout/_header.html
<header>
	<nav class="blue darken-2" role="navigation">
		<div class="nav-wrapper container">
			<a id="logo-container" href="{{ url_for('home.index') }}" class="brand-logo">TransLang </a>
			{% if current_user.is_anonymous %}
			<!-- Logged out navbar -->
			<ul class="right hide-on-med-and-down">
				<li><a href="{{ url_for('auth.register') }}">Register</a></li>
				<li><a href="{{ url_for('auth.login') }}">Login</a></li>
			</ul>
			<ul id="nav-mobile" class="sidenav">
				<li><a href="{{ url_for('auth.register') }}">Register</a></li>
				<li><a href="{{ url_for('auth.login') }}">Login</a></li>
			</ul>
			{% else %}
			<!-- Logged in navbar -->
			<ul class="right hide-on-med-and-down">
				<li>
					<a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a>
				</li>
				<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
			</ul>
			<ul id="nav-mobile" class="sidenav">
				<li>
					<a href="{{ url_for('dashboard.dashboard') }}">Dashboard</a>
				</li>
				<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
			</ul>
			{% endif %}
			<a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		</div>
	</nav>
</header>

app/templates/_partials/form/cancel.html
<a href="{{ cancel_url }}" class="btn waves-effect waves-light red">
  Cancel
</a>

app/templates/_partials/form/email.html
<div class="input-field">
  {{ form.email.label }} {{ form.email(size=64, class="validate") }}
  <!--  -->
  {% for error in form.email.errors %}
  <span class="helper-text" data-error="" data-success="">
    {{ error }}
  </span>
  {% endfor %}
</div>

app/templates/_partials/form/password.html
<div class="input-field">
  {{ form.password.label }} {{ form.password(size=32, class="validate") }}
  <!--  -->
  {% for error in form.password.errors %}
  <span class="helper-text" data-error="wrong" data-success="right">
    {{ error }}
  </span>
  {% endfor %}
</div>

{% if password_confirm %}
<div class="input-field">
  {{ form.password_confirm.label }}
  {{ form.password_confirm(size=32, class="validate") }}
  {% for error in form.password_confirm.errors %}
  <span style="color: red;">[{{ error }}]</span>
  {% endfor %}
</div>
{% endif %}

app/templates/_partials/form/remember-me.html
<p>
  <label>
    <input type="checkbox" class="filled-in" />
    <span>Remember me</span>
  </label>
</p>

<!-- <p>
    form.remember_me(class="filled-in") form.remember_me.label
  </p> -->

app/templates/_partials/form/submit.html
<button class="btn waves-effect waves-light light-green">
  Submit
</button>

app/templates/base.html
<html>
	<head>
		{% if title %}
		<title>{{ title }}</title>
		{% else %}
		<title>Welcome</title>
		{% endif %}

		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- Compiled and minified CSS -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/materialize.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
		<style>
			#translate-button:focus {
				outline: 3px solid #1565c0 !important;
			}
			#exchange-languages:hover {
				cursor: pointer;
			}
			#start-speech:hover {
				cursor: pointer;
			}
			#start-dictation:hover {
				cursor: pointer;
			}
		</style>
	</head>
	<body class="{{ 'overflow-hidden' if full_page_width }}">
		<!-- Header -->
		{% include '_layout/_header.html' %}

		<!-- Main -->
		<main class="main container">
			<!-- Flashed messages -->
			{% include '_layout/_flash_messages.html' %}

			<!-- Block content -->
			{% block content %} {% endblock %}
		</main>

		<!-- Footer -->
		{% include '_layout/_footer.html' %}

		<!-- Compiled and minified JavaScript -->
		<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
		<script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
		<script src="{{ url_for('static', filename='js/main.js') }}"></script>
		<script>
			function startDictation() {
				if (window.hasOwnProperty("webkitSpeechRecognition")) {
					var recognition = new webkitSpeechRecognition();
					recognition.continuous = false;
					recognition.interimResults = false;
					recognition.lang = document.getElementById("lang_from").value;
					recognition.start();

					recognition.onresult = function (e) {
						document.getElementsByClassName("text-from")[0].value = e.results[0][0].transcript;
						recognition.stop();
					};
					recognition.onerror = function (e) {
						recognition.stop();
					};
				}
			}
			var startDictationIcon = document.querySelector("#start-dictation");
			if (startDictationIcon) {
				startDictationIcon.addEventListener("click", startDictation);
				startDictationIcon.addEventListener("keyup", function () {
					if (event.keyCode === 13) {
						startDictation();
					}
				});
			}

			function startSpeech() {
				var synth = window.speechSynthesis;
				text = document.getElementById("text-to").value;
				var utterThis = new SpeechSynthesisUtterance(text);
				utterThis.lang = document.getElementById("lang_to").value;
				synth.speak(utterThis);
			}
			var startSpeechIcon = document.querySelector("#start-speech");
			if (startSpeechIcon) {
				startSpeechIcon.addEventListener("click", startSpeech);
				startSpeechIcon.addEventListener("keyup", function () {
					if (event.keyCode === 13) {
						startSpeech();
					}
				});
			}

			function exchangeLanguages() {
				var langTo = $("#lang_to").val();
				var langFrom = $("#lang_from").val();
				$("#lang_to").val(langFrom);
				$("#lang_from").val(langTo);
				$("select").formSelect();
			}
			var exchangeLanguagesIcon = document.querySelector("#exchange-languages");
			if (exchangeLanguagesIcon) {
				exchangeLanguagesIcon.addEventListener("click", exchangeLanguages);
				exchangeLanguagesIcon.addEventListener("keyup", function () {
					if (event.keyCode === 13) {
						exchangeLanguages();
					}
				});
			}
		</script>
	</body>
</html>

app/templates/dashboard/dashboard.html
{% extends "base.html" %}

<!-- start block -->
{% block content %}

<div class="row">
	<div class="col s12 m5">
		<div class="card darken-1">
			<div class="card-content">
				<span class="card-title">Account Settings</span>
				<p>Email: {{user.email}}</p>
				<p>Default Language (from):</p>
				<p>Default Language (to):</p>
			</div>
			<div class="card-action">
				<a href="#">Change Password</a>
				<a href="#">Change Email</a>
			</div>
		</div>
	</div>
	<div class="col s12 m7">
		<ul class="collection with-header">
			<li class="collection-header"><h4>Latest Translations</h4></li>
			{% for t in latest_translations %}
			<li class="collection-item">
				<div>
					<a class="previous_trans" href="{{url_for('home.index', translation_id=t.id)}}">
						<strong>({{t.lang_from}} -> {{t.lang_to}})</strong> {{t.text_from}} {#
						<a href="#!" class="secondary-content"><i class="material-icons">send</i></a> #}
					</a>
				</div>
			</li>

			{% endfor %}
		</ul>
	</div>
</div>

{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}

<!-- start block -->
{% block content %}

<div class="section no-pad-bot" id="index-banner">
	<div class="row center-align">
		<form class="col s12" method="POST">
			{{form.hidden_tag()}}
			<div class="row">
				<div class="card col s12">
					<div class="card-content">
						<button
							tabindex="0"
							id="translate-button"
							class="waves-effect waves-light btn orange lighten-1"
						>
							Translate
						</button>

						<div class="input-field col s12">
							<div class="input-field col s12 m5">{{form.lang_from}}</div>
							<div class="input-field col s12 m2">
								<i tabindex="0" id="exchange-languages" class="medium material-icons grey-text"
									>swap_horiz</i
								>
							</div>
							<div class="input-field col s12 m5 ">{{form.lang_to}}</div>
						</div>
						<div class="input-field col s12 m6">
							<textarea class="text-from materialize-textarea">{{translation.text_from or ''}}</textarea>

							<i
								id="start-dictation"
								tabindex="0"
								style="position: absolute; right: 1rem; bottom: 0.8rem"
								class="small material-icons grey-text"
								>keyboard_voice</i
							>
						</div>

						<div class="input-field col s12 m6">
							<textarea disabled id="text-to" class="materialize-textarea grey lighten-4">
{{translation.text_to or translated_text}}</textarea
							>
							<label for="text-to"></label>
							<i
								id="start-speech"
								tabindex="0"
								style="position: absolute; right: 1rem; bottom: 0.8rem"
								class="small material-icons grey-text"
								>volume_up</i
							>
						</div>
					</div>
				</div>
			</div>
		</form>

		<div class="section">
			<!--   Icon Section   -->
			{#
			<div class="row">
				<div class="card">
					<div class="card-content">
						{% if current_user.is_anonymous %}
						<h4 class="center-align">Sign up to save your translation history!</h4>
						{% else %}
						<h4>Your latest translations:</h4>
						{% for i in last_translations %}
						<blockquote><strong>({{i.lang_from}} -> {{i.lang_to}})</strong> {{i.text_from}}</blockquote>
						{% endfor %}
						<!--  -->
						{% endif %}
					</div>
				</div>
			</div>
			#}

			<div class="col s12">
				<h2 class="header">About TransLang</h2>
				<div class="card horizontal">
					<div class="card-image">
						<img src="https://ece.uwaterloo.ca/~dwharder/Flags/images/fotw.1000.png" />
					</div>
					<div class="card-stacked">
						<div class="card-content">
							<p>
								TransLang is a translation service based on cloud machine learning APIs that provides a
								convenient way to translate between hundreads of pairs of languages
							</p>
						</div>
						<div class="card-action">
							{% if current_user.is_anonymous %}
							<a href="{{url_for('auth.register')}}"> Sign up to save your translation history </a>
							{% else %}
							<a href="{{url_for('dashboard.dashboard')}}"> View your translation history </a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- end block  -->
		{% endblock %}
	</div>
</div>